# NumPy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [11]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [39]:
my_mat = [[1, 2, 3], [4, 6, 7], [7, 8, 4, 9]]

In [40]:
np.array(my_mat)

array([list([1, 2, 3]), list([4, 6, 7]), list([7, 8, 4, 9])], dtype=object)

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.zeros((5, 5, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.linspace(1, 2, 4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(4)

array([0.80056548, 0.51886908, 0.19885551, 0.69922345])

In [5]:
np.random.rand(3, 3)

array([[0.33736952, 0.12605351, 0.13118818],
       [0.78057211, 0.06577921, 0.59402643],
       [0.5808877 , 0.98936902, 0.0499112 ]])

In [22]:
np.random.randn(6)

array([-0.70838929,  0.05202679,  1.18747067, -1.03269354,  0.37368858,
        0.2743614 ])

In [23]:
np.random.randint(1, 100, (2, 2))

array([[67, 88],
       [42, 62]])

In [25]:
np.random.randint(1, 10)

4

In [7]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ran_arr = np.random.randint(0, 50, 10)

In [29]:
ran_arr

array([47, 19, 16, 34, 36, 32, 30, 34, 42, 12])

In [14]:
res = arr.reshape(5, 5)
res[24]

IndexError: index 24 is out of bounds for axis 0 with size 5

In [9]:
res.max()

24

In [15]:
res.argmax()

24

In [32]:
ran_arr.max()

47

In [33]:
max(ran_arr)

47

In [34]:
ran_arr.min()

12

In [35]:
ran_arr.argmax()

0

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(5, 5).shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')